#!/bin/bash


WIKI-CONT
WIKI-CONT-nodedup
KOSARAK-CONT-nodedup
OPEN-Jaccard08
WIKI-CONT-lenshuf
OPEN-CONT-lenshuf
AOL-CONT-lenshuf
WIKI-CONT
OPEN-JACCARD-DEDUP

find ./WIKI-CONT -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_WIKI-CONT.csv

find ./WIKI-CONT-nodedup -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_WIKI-CONT-nodedup.csv

find ./KOSARAK-CONT-nodedup -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_KOSARAK-CONT-nodedup.csv

find ./OPEN-Jaccard08 -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_OPEN-Jaccard08.csv

find ./WIKI-CONT-lenshuf -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_WIKI-CONT-lenshuf.csv

find ./OPEN-CONT-lenshuf -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_OPEN-CONT-lenshuf.csv

find ./AOL-CONT-lenshuf -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_AOL-CONT-lenshuf.csv

find ./WIKI-CONT -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_WIKI-CONT.csv

find ./OPEN-JACCARD-DEDUP -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_OPEN-JACCARD-DEDUP.csv

find ./OPEN-CONT -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_OPEN_CONT.csv



find ./AOL-CONT-XX -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_AOL-CONT-XX.csv

find ./BMS-CONT -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_BMS-CONT.csv

find ./BMS-CONT-XX -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_BMS-CONT-XX.csv

find ./DBLP-2q-CONT -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_DBLP-2q-CONT.csv

find ./DBLP-2q-CONT-XX -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_DBLP-2q-CONT-XX.csv

find ./ENRON-CONT -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_ENRON-CONT.csv

find ./ENRON-CONT-XX -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_ENRON-CONT-XX.csv

find ./KOSARAK-CONT -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_KOSARAK-CONT.csv

find ./KOSARAK-CONT-XX -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_KOSARAK-CONT-XX.csv

find ./LIVE-CONT -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_LIVE-CONT.csv

find ./LIVE-CONT-XX -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_LIVE-CONT-XX.csv

find ./OPEN-CONT  -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_OPEN-CONT.csv

find ./OPEN-CONT-XX -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_OPEN-CONT-XX.csv

find ./OPEN-CONT-nodedup -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_OPEN-CONT-nodedup.csv

find ./OPEN-CONT-XX-nodedup -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_OPEN-CONT-XX-nodedup.csv

find ./ORKUT-CONT -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_ORKUT-CONT.csv

find ./UNIF-CONT -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_UNIF-CONT.csv

find ./UNIF-CONT-XX -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_UNIF-CONT-XX.csv

find ./ZIPF-CONT -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_ZIPF-CONT.csv

find ./ZIPF-CONT1-XX -type f -print0 | xargs -0 -n100 -P0  python3 convertOutput.py
mv output.csv output_ZIPF-CONT1-XX.csv







